spring:
  datasource:
    url: jdbc:h2:mem:localDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /console

logging.level:
  org.hibernate.SQL: debug