spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bulletin-board.cbrjnofn07hp.ap-northeast-2.rds.amazonaws.com:3306/bulletin_board?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: none